### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by srwxr-xr-x** [ValemVR/VR-Game-Jam-Template#1]
What license does this project use? Are we allowed to use this commercially?

**Comment by ValemVR** [comment]
I just added a license to make this project follow the Unity XR 2.3 demo license which used Unity Companion License. You can read more about it here ; http://www.unity3d.com/legal/licenses/Unity_Companion_License

**Comment by ValemVR** [comment]
I just added a license to make this project follow the Unity XR 2.3 demo license which used Unity Companion License. You can read more about it here ; http://www.unity3d.com/legal/licenses/Unity_Companion_License
